theme: jekyll-theme-minimal


domain: laskstudio.com
company: LaskStudio
company_address: 
company_support_email: support@laskstudio.com

bikesto:
  title: bikesTO
  destination: Toronto
  aup_link: https://laskstudio.com/bikesto/aup
  privacy_link: https://laskstudio.com/bikesto/privacy-policy
  disclaimer_link: https://laskstudio.com/bikesto/disclaimer
  website: https://laskstudio.com/bikesto
  support_email: support.bikesto@laskstudio.com

domain: laskstudio.com
company: LaskStudio
company_address: 
company_support_email: support@laskstudio.com
